server:
  port: 9000

spring:
  application:
    name: edge-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:9004}/auths
          predicates:
            - Path=/auths/**
